title: Fabien Baeriswyl
logo: Pic-Up.png
baseurl: https://www.fabienbaeriswyl.fr
description-fr: "Bienvenue sur ma page personnelle! Je suis actuellement en thèse entre Lausanne et Paris, dans des domaines qui se situent entre les probabilités appliquées et la statistique. Je m'intéresse également aux applications climatiques et actuarielles. Vous trouverez ci-dessous mes informations de contact et, sur le menu déroulant à droite, de plus amples informations à mon propos.
  "
description-en: "Welcome to my homepage! I am currently doing my thesis between Lausanne and Paris, in domains at the intersection between applied probability and statistics. I am also interested in climate as well as actuarial applications. You will find below contact information and, on the right panel, more information about myself. "
theme: jekyll-theme-minimal
author:
  email: "fabien.baeriswyl@sorbonne-universite.fr"
  email2: "fabien.baeriswyl@unil.ch"
  orcid: "https://orcid.org/0000-0001-5429-7303"
  googlescholar: "https://scholar.google.com/citations?user=xSfL1WQAAAAJ&hl=fr"
gems:
  - jekyll-email-protect
  - jemoji

