title: ----------------
logo: Pic-Up.png
url: "https://fabienbaeriswyl.github.io"
baseurl: /fabienbaeriswyl
plugins: 
  - jemoji
  - jekyll-sitemap
theme: jekyll-theme-minimal
author:
  email: ":email: fabien.baeriswyl at sorbonne-universite dot fr" 
  email2: ":email: fabien.baeriswyl at unil dot ch"
