title: ----------------
logo: Pic-Up.png
social-network-links:
  email: :email: fabien.baeriswyl at sorbonne-universite dot fr
  email: :email: fabien.baeriswyl at unil dot ch 
plugins: 
- jemoji
theme: jekyll-theme-minimal
